package mindstorms17;
import lejos.hardware.lcd.LCD;
import lejos.hardware.motor.EV3LargeRegulatedMotor;
import lejos.hardware.port.MotorPort;
import lejos.hardware.port.SensorPort;
import lejos.hardware.sensor.EV3ColorSensor;
import lejos.hardware.sensor.EV3TouchSensor;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class Main {

	public static void main(String[] args) throws InterruptedException, IOException {

		// SOA applied here
		// ATTENTION: the head is down at start;
		
		// CHAPTER 1: init robot object
		Robot myRobot = new Robot(0,0,true,
				new EV3LargeRegulatedMotor(MotorPort.A), // chainMotor
				new EV3LargeRegulatedMotor(MotorPort.B), // wheelMotor
				new EV3LargeRegulatedMotor(MotorPort.C), // headMotor
				new EV3TouchSensor(SensorPort.S1), // touchSensor
				new EV3ColorSensor(SensorPort.S2)); // colorSensor

		
		
		//CHAPTER 2: getting the image and processing it
		LCD.clear();LCD.drawString("Img processing ...", 0, 0);
		ImageService img1 = new ImageService();
		/*img1.load(ImageIO.read(new File("src/graphics/apple_logo.png")));
		img1.verify();
		img1.canny();
		img1.positionCreator();
		img1.exportPositions();*/

		//TODO: if this stuff works, OPTIMISE !!! 
		//TODO: first position shall be headSwitch true, because head down at the start after driveToHome()
		img1.positions.add( new Position(99, 8, true)); 
		img1.positions.add( new Position(100, 8, true)); 
		img1.positions.add( new Position(99, 8, false)); 
		img1.positions.add( new Position(98, 9, false)); 
		img1.positions.add( new Position(97, 9, false)); 
		img1.positions.add( new Position(96, 9, false)); 
		img1.positions.add( new Position(95, 9, false)); 
		img1.positions.add( new Position(95, 10, false)); 
		img1.positions.add( new Position(94, 10, false)); 
		img1.positions.add( new Position(93, 10, false)); 
		img1.positions.add( new Position(92, 11, false)); 
		img1.positions.add( new Position(91, 11, false)); 
		img1.positions.add( new Position(90, 12, false)); 
		img1.positions.add( new Position(89, 12, false)); 
		img1.positions.add( new Position(89, 13, false)); 
		img1.positions.add( new Position(88, 13, false)); 
		img1.positions.add( new Position(87, 13, false)); 
		img1.positions.add( new Position(87, 14, false)); 
		img1.positions.add( new Position(86, 14, false)); 
		img1.positions.add( new Position(86, 15, false)); 
		img1.positions.add( new Position(85, 15, false)); 
		img1.positions.add( new Position(85, 16, false)); 
		img1.positions.add( new Position(84, 16, false)); 
		img1.positions.add( new Position(84, 17, false)); 
		img1.positions.add( new Position(83, 17, false)); 
		img1.positions.add( new Position(83, 18, false)); 
		img1.positions.add( new Position(82, 18, false)); 
		img1.positions.add( new Position(82, 19, false)); 
		img1.positions.add( new Position(81, 19, false)); 
		img1.positions.add( new Position(81, 20, false)); 
		img1.positions.add( new Position(80, 20, false)); 
		img1.positions.add( new Position(80, 21, false)); 
		img1.positions.add( new Position(79, 22, false)); 
		img1.positions.add( new Position(79, 23, false)); 
		img1.positions.add( new Position(78, 23, false)); 
		img1.positions.add( new Position(78, 24, false)); 
		img1.positions.add( new Position(78, 25, false)); 
		img1.positions.add( new Position(77, 25, false)); 
		img1.positions.add( new Position(77, 26, false)); 
		img1.positions.add( new Position(77, 27, false)); 
		img1.positions.add( new Position(76, 27, false)); 
		img1.positions.add( new Position(76, 28, false)); 
		img1.positions.add( new Position(76, 29, false)); 
		img1.positions.add( new Position(75, 30, false)); 
		img1.positions.add( new Position(75, 31, false)); 
		img1.positions.add( new Position(75, 32, false)); 
		img1.positions.add( new Position(75, 33, false)); 
		img1.positions.add( new Position(75, 34, false)); 
		img1.positions.add( new Position(75, 35, false)); 
		img1.positions.add( new Position(75, 36, false)); 
		img1.positions.add( new Position(75, 37, false)); 
		img1.positions.add( new Position(75, 38, false)); 
		img1.positions.add( new Position(76, 38, false)); 
		img1.positions.add( new Position(76, 39, false)); 
		img1.positions.add( new Position(77, 39, false)); 
		img1.positions.add( new Position(78, 39, false)); 
		img1.positions.add( new Position(79, 39, false)); 
		img1.positions.add( new Position(80, 39, false)); 
		img1.positions.add( new Position(81, 38, false)); 
		img1.positions.add( new Position(82, 38, false)); 
		img1.positions.add( new Position(83, 38, false)); 
		img1.positions.add( new Position(84, 37, false)); 
		img1.positions.add( new Position(85, 37, false)); 
		img1.positions.add( new Position(86, 37, false)); 
		img1.positions.add( new Position(86, 36, false)); 
		img1.positions.add( new Position(87, 36, false)); 
		img1.positions.add( new Position(88, 36, false)); 
		img1.positions.add( new Position(88, 35, false)); 
		img1.positions.add( new Position(89, 35, false)); 
		img1.positions.add( new Position(89, 34, false)); 
		img1.positions.add( new Position(90, 34, false)); 
		img1.positions.add( new Position(91, 34, false)); 
		img1.positions.add( new Position(91, 33, false)); 
		img1.positions.add( new Position(92, 33, false)); 
		img1.positions.add( new Position(92, 32, false)); 
		img1.positions.add( new Position(93, 32, false)); 
		img1.positions.add( new Position(93, 31, false)); 
		img1.positions.add( new Position(94, 31, false)); 
		img1.positions.add( new Position(94, 30, false)); 
		img1.positions.add( new Position(95, 30, false)); 
		img1.positions.add( new Position(95, 29, false)); 
		img1.positions.add( new Position(96, 29, false)); 
		img1.positions.add( new Position(96, 28, false)); 
		img1.positions.add( new Position(96, 27, false)); 
		img1.positions.add( new Position(97, 27, false)); 
		img1.positions.add( new Position(97, 26, false)); 
		img1.positions.add( new Position(98, 26, false)); 
		img1.positions.add( new Position(98, 25, false)); 
		img1.positions.add( new Position(98, 24, false)); 
		img1.positions.add( new Position(99, 24, false)); 
		img1.positions.add( new Position(99, 23, false)); 
		img1.positions.add( new Position(100, 22, false)); 
		img1.positions.add( new Position(100, 21, false)); 
		img1.positions.add( new Position(101, 20, false)); 
		img1.positions.add( new Position(101, 19, false)); 
		img1.positions.add( new Position(101, 18, false)); 
		img1.positions.add( new Position(101, 17, false)); 
		img1.positions.add( new Position(102, 17, false)); 
		img1.positions.add( new Position(102, 16, false)); 
		img1.positions.add( new Position(102, 15, false)); 
		img1.positions.add( new Position(102, 14, false)); 
		img1.positions.add( new Position(102, 13, false)); 
		img1.positions.add( new Position(102, 12, false)); 
		img1.positions.add( new Position(102, 11, false)); 
		img1.positions.add( new Position(102, 10, false)); 
		img1.positions.add( new Position(102, 9, false)); 
		img1.positions.add( new Position(101, 9, false)); 
		img1.positions.add( new Position(97, 39, true)); 
		img1.positions.add( new Position(98, 39, true)); 
		img1.positions.add( new Position(99, 39, false)); 
		img1.positions.add( new Position(100, 39, false)); 
		img1.positions.add( new Position(101, 39, false)); 
		img1.positions.add( new Position(102, 39, false)); 
		img1.positions.add( new Position(103, 39, false)); 
		img1.positions.add( new Position(104, 40, false)); 
		img1.positions.add( new Position(105, 40, false)); 
		img1.positions.add( new Position(106, 40, false)); 
		img1.positions.add( new Position(107, 40, false)); 
		img1.positions.add( new Position(108, 40, false)); 
		img1.positions.add( new Position(109, 41, false)); 
		img1.positions.add( new Position(110, 41, false)); 
		img1.positions.add( new Position(111, 41, false)); 
		img1.positions.add( new Position(112, 41, false)); 
		img1.positions.add( new Position(112, 42, false)); 
		img1.positions.add( new Position(113, 42, false)); 
		img1.positions.add( new Position(114, 42, false)); 
		img1.positions.add( new Position(115, 43, false)); 
		img1.positions.add( new Position(116, 43, false)); 
		img1.positions.add( new Position(117, 44, false)); 
		img1.positions.add( new Position(118, 44, false)); 
		img1.positions.add( new Position(118, 45, false)); 
		img1.positions.add( new Position(119, 45, false)); 
		img1.positions.add( new Position(120, 45, false)); 
		img1.positions.add( new Position(120, 46, false)); 
		img1.positions.add( new Position(121, 46, false)); 
		img1.positions.add( new Position(121, 47, false)); 
		img1.positions.add( new Position(122, 47, false)); 
		img1.positions.add( new Position(122, 48, false)); 
		img1.positions.add( new Position(123, 48, false)); 
		img1.positions.add( new Position(123, 49, false)); 
		img1.positions.add( new Position(124, 49, false)); 
		img1.positions.add( new Position(124, 50, false)); 
		img1.positions.add( new Position(125, 50, false)); 
		img1.positions.add( new Position(125, 51, false)); 
		img1.positions.add( new Position(125, 52, false)); 
		img1.positions.add( new Position(125, 53, false)); 
		img1.positions.add( new Position(125, 54, false)); 
		img1.positions.add( new Position(124, 54, false)); 
		img1.positions.add( new Position(124, 55, false)); 
		img1.positions.add( new Position(123, 55, false)); 
		img1.positions.add( new Position(123, 56, false)); 
		img1.positions.add( new Position(122, 56, false)); 
		img1.positions.add( new Position(121, 57, false)); 
		img1.positions.add( new Position(120, 57, false)); 
		img1.positions.add( new Position(120, 58, false)); 
		img1.positions.add( new Position(119, 58, false)); 
		img1.positions.add( new Position(119, 59, false)); 
		img1.positions.add( new Position(118, 60, false)); 
		img1.positions.add( new Position(118, 61, false)); 
		img1.positions.add( new Position(117, 61, false)); 
		img1.positions.add( new Position(117, 62, false)); 
		img1.positions.add( new Position(116, 62, false)); 
		img1.positions.add( new Position(116, 63, false)); 
		img1.positions.add( new Position(116, 64, false)); 
		img1.positions.add( new Position(115, 64, false)); 
		img1.positions.add( new Position(115, 65, false)); 
		img1.positions.add( new Position(114, 66, false)); 
		img1.positions.add( new Position(114, 67, false)); 
		img1.positions.add( new Position(114, 68, false)); 
		img1.positions.add( new Position(113, 68, false)); 
		img1.positions.add( new Position(113, 69, false)); 
		img1.positions.add( new Position(113, 70, false)); 
		img1.positions.add( new Position(113, 71, false)); 
		img1.positions.add( new Position(113, 72, false)); 
		img1.positions.add( new Position(112, 73, false)); 
		img1.positions.add( new Position(112, 74, false)); 
		img1.positions.add( new Position(112, 75, false)); 
		img1.positions.add( new Position(112, 76, false)); 
		img1.positions.add( new Position(112, 77, false)); 
		img1.positions.add( new Position(112, 78, false)); 
		img1.positions.add( new Position(112, 79, false)); 
		img1.positions.add( new Position(112, 80, false)); 
		img1.positions.add( new Position(112, 81, false)); 
		img1.positions.add( new Position(112, 82, false)); 
		img1.positions.add( new Position(112, 83, false)); 
		img1.positions.add( new Position(113, 83, false)); 
		img1.positions.add( new Position(113, 84, false)); 
		img1.positions.add( new Position(113, 85, false)); 
		img1.positions.add( new Position(113, 86, false)); 
		img1.positions.add( new Position(113, 87, false)); 
		img1.positions.add( new Position(114, 88, false)); 
		img1.positions.add( new Position(114, 89, false)); 
		img1.positions.add( new Position(114, 90, false)); 
		img1.positions.add( new Position(115, 90, false)); 
		img1.positions.add( new Position(115, 91, false)); 
		img1.positions.add( new Position(115, 92, false)); 
		img1.positions.add( new Position(116, 92, false)); 
		img1.positions.add( new Position(116, 93, false)); 
		img1.positions.add( new Position(117, 94, false)); 
		img1.positions.add( new Position(117, 95, false)); 
		img1.positions.add( new Position(118, 95, false)); 
		img1.positions.add( new Position(118, 96, false)); 
		img1.positions.add( new Position(119, 96, false)); 
		img1.positions.add( new Position(119, 97, false)); 
		img1.positions.add( new Position(120, 97, false)); 
		img1.positions.add( new Position(120, 98, false)); 
		img1.positions.add( new Position(121, 98, false)); 
		img1.positions.add( new Position(121, 99, false)); 
		img1.positions.add( new Position(122, 99, false)); 
		img1.positions.add( new Position(122, 100, false)); 
		img1.positions.add( new Position(123, 100, false)); 
		img1.positions.add( new Position(123, 101, false)); 
		img1.positions.add( new Position(124, 101, false)); 
		img1.positions.add( new Position(124, 102, false)); 
		img1.positions.add( new Position(125, 102, false)); 
		img1.positions.add( new Position(126, 103, false)); 
		img1.positions.add( new Position(127, 103, false)); 
		img1.positions.add( new Position(127, 104, false)); 
		img1.positions.add( new Position(128, 104, false)); 
		img1.positions.add( new Position(128, 105, false)); 
		img1.positions.add( new Position(129, 105, false)); 
		img1.positions.add( new Position(129, 106, false)); 
		img1.positions.add( new Position(129, 107, false)); 
		img1.positions.add( new Position(129, 108, false)); 
		img1.positions.add( new Position(129, 109, false)); 
		img1.positions.add( new Position(128, 110, false)); 
		img1.positions.add( new Position(128, 111, false)); 
		img1.positions.add( new Position(128, 112, false)); 
		img1.positions.add( new Position(127, 112, false)); 
		img1.positions.add( new Position(127, 113, false)); 
		img1.positions.add( new Position(127, 114, false)); 
		img1.positions.add( new Position(126, 114, false)); 
		img1.positions.add( new Position(126, 115, false)); 
		img1.positions.add( new Position(126, 116, false)); 
		img1.positions.add( new Position(125, 116, false)); 
		img1.positions.add( new Position(125, 117, false)); 
		img1.positions.add( new Position(125, 118, false)); 
		img1.positions.add( new Position(124, 118, false)); 
		img1.positions.add( new Position(124, 119, false)); 
		img1.positions.add( new Position(124, 120, false)); 
		img1.positions.add( new Position(123, 120, false)); 
		img1.positions.add( new Position(123, 121, false)); 
		img1.positions.add( new Position(122, 122, false)); 
		img1.positions.add( new Position(122, 123, false)); 
		img1.positions.add( new Position(121, 123, false)); 
		img1.positions.add( new Position(121, 124, false)); 
		img1.positions.add( new Position(120, 125, false)); 
		img1.positions.add( new Position(120, 126, false)); 
		img1.positions.add( new Position(119, 126, false)); 
		img1.positions.add( new Position(119, 127, false)); 
		img1.positions.add( new Position(118, 127, false)); 
		img1.positions.add( new Position(118, 128, false)); 
		img1.positions.add( new Position(117, 129, false)); 
		img1.positions.add( new Position(117, 130, false)); 
		img1.positions.add( new Position(116, 130, false)); 
		img1.positions.add( new Position(116, 131, false)); 
		img1.positions.add( new Position(115, 131, false)); 
		img1.positions.add( new Position(115, 132, false)); 
		img1.positions.add( new Position(114, 132, false)); 
		img1.positions.add( new Position(114, 133, false)); 
		img1.positions.add( new Position(113, 133, false)); 
		img1.positions.add( new Position(113, 134, false)); 
		img1.positions.add( new Position(112, 134, false)); 
		img1.positions.add( new Position(112, 135, false)); 
		img1.positions.add( new Position(111, 135, false)); 
		img1.positions.add( new Position(111, 136, false)); 
		img1.positions.add( new Position(110, 136, false)); 
		img1.positions.add( new Position(110, 137, false)); 
		img1.positions.add( new Position(109, 137, false)); 
		img1.positions.add( new Position(108, 137, false)); 
		img1.positions.add( new Position(108, 138, false)); 
		img1.positions.add( new Position(107, 138, false)); 
		img1.positions.add( new Position(106, 139, false)); 
		img1.positions.add( new Position(105, 139, false)); 
		img1.positions.add( new Position(104, 140, false)); 
		img1.positions.add( new Position(103, 140, false)); 
		img1.positions.add( new Position(102, 140, false)); 
		img1.positions.add( new Position(101, 140, false)); 
		img1.positions.add( new Position(100, 140, false)); 
		img1.positions.add( new Position(99, 140, false)); 
		img1.positions.add( new Position(98, 140, false)); 
		img1.positions.add( new Position(97, 140, false)); 
		img1.positions.add( new Position(96, 140, false)); 
		img1.positions.add( new Position(95, 140, false)); 
		img1.positions.add( new Position(94, 139, false)); 
		img1.positions.add( new Position(93, 139, false)); 
		img1.positions.add( new Position(92, 139, false)); 
		img1.positions.add( new Position(91, 139, false)); 
		img1.positions.add( new Position(91, 138, false)); 
		img1.positions.add( new Position(90, 138, false)); 
		img1.positions.add( new Position(89, 138, false)); 
		img1.positions.add( new Position(88, 137, false)); 
		img1.positions.add( new Position(87, 137, false)); 
		img1.positions.add( new Position(86, 137, false)); 
		img1.positions.add( new Position(85, 136, false)); 
		img1.positions.add( new Position(84, 136, false)); 
		img1.positions.add( new Position(83, 136, false)); 
		img1.positions.add( new Position(82, 136, false)); 
		img1.positions.add( new Position(81, 136, false)); 
		img1.positions.add( new Position(80, 135, false)); 
		img1.positions.add( new Position(79, 135, false)); 
		img1.positions.add( new Position(78, 135, false)); 
		img1.positions.add( new Position(77, 135, false)); 
		img1.positions.add( new Position(76, 135, false)); 
		img1.positions.add( new Position(75, 135, false)); 
		img1.positions.add( new Position(74, 135, false)); 
		img1.positions.add( new Position(73, 136, false)); 
		img1.positions.add( new Position(72, 136, false)); 
		img1.positions.add( new Position(71, 136, false)); 
		img1.positions.add( new Position(70, 136, false)); 
		img1.positions.add( new Position(69, 136, false)); 
		img1.positions.add( new Position(69, 137, false)); 
		img1.positions.add( new Position(68, 137, false)); 
		img1.positions.add( new Position(67, 137, false)); 
		img1.positions.add( new Position(66, 137, false)); 
		img1.positions.add( new Position(66, 138, false)); 
		img1.positions.add( new Position(65, 138, false)); 
		img1.positions.add( new Position(64, 138, false)); 
		img1.positions.add( new Position(63, 138, false)); 
		img1.positions.add( new Position(63, 139, false)); 
		img1.positions.add( new Position(62, 139, false)); 
		img1.positions.add( new Position(61, 139, false)); 
		img1.positions.add( new Position(60, 139, false)); 
		img1.positions.add( new Position(60, 140, false)); 
		img1.positions.add( new Position(59, 140, false)); 
		img1.positions.add( new Position(58, 140, false)); 
		img1.positions.add( new Position(57, 140, false)); 
		img1.positions.add( new Position(56, 140, false)); 
		img1.positions.add( new Position(55, 140, false)); 
		img1.positions.add( new Position(54, 140, false)); 
		img1.positions.add( new Position(53, 140, false)); 
		img1.positions.add( new Position(52, 140, false)); 
		img1.positions.add( new Position(51, 140, false)); 
		img1.positions.add( new Position(50, 140, false)); 
		img1.positions.add( new Position(49, 139, false)); 
		img1.positions.add( new Position(48, 139, false)); 
		img1.positions.add( new Position(47, 138, false)); 
		img1.positions.add( new Position(46, 138, false)); 
		img1.positions.add( new Position(46, 137, false)); 
		img1.positions.add( new Position(45, 137, false)); 
		img1.positions.add( new Position(44, 137, false)); 
		img1.positions.add( new Position(44, 136, false)); 
		img1.positions.add( new Position(43, 136, false)); 
		img1.positions.add( new Position(43, 135, false)); 
		img1.positions.add( new Position(42, 135, false)); 
		img1.positions.add( new Position(42, 134, false)); 
		img1.positions.add( new Position(41, 134, false)); 
		img1.positions.add( new Position(41, 133, false)); 
		img1.positions.add( new Position(40, 133, false)); 
		img1.positions.add( new Position(40, 132, false)); 
		img1.positions.add( new Position(39, 132, false)); 
		img1.positions.add( new Position(39, 131, false)); 
		img1.positions.add( new Position(38, 131, false)); 
		img1.positions.add( new Position(38, 130, false)); 
		img1.positions.add( new Position(37, 129, false)); 
		img1.positions.add( new Position(37, 128, false)); 
		img1.positions.add( new Position(36, 128, false)); 
		img1.positions.add( new Position(36, 127, false)); 
		img1.positions.add( new Position(35, 127, false)); 
		img1.positions.add( new Position(35, 126, false)); 
		img1.positions.add( new Position(34, 126, false)); 
		img1.positions.add( new Position(34, 125, false)); 
		img1.positions.add( new Position(34, 124, false)); 
		img1.positions.add( new Position(33, 124, false)); 
		img1.positions.add( new Position(33, 123, false)); 
		img1.positions.add( new Position(32, 123, false)); 
		img1.positions.add( new Position(32, 122, false)); 
		img1.positions.add( new Position(32, 121, false)); 
		img1.positions.add( new Position(31, 121, false)); 
		img1.positions.add( new Position(31, 120, false)); 
		img1.positions.add( new Position(30, 120, false)); 
		img1.positions.add( new Position(30, 119, false)); 
		img1.positions.add( new Position(30, 118, false)); 
		img1.positions.add( new Position(29, 118, false)); 
		img1.positions.add( new Position(29, 117, false)); 
		img1.positions.add( new Position(29, 116, false)); 
		img1.positions.add( new Position(28, 116, false)); 
		img1.positions.add( new Position(28, 115, false)); 
		img1.positions.add( new Position(28, 114, false)); 
		img1.positions.add( new Position(27, 114, false)); 
		img1.positions.add( new Position(27, 113, false)); 
		img1.positions.add( new Position(27, 112, false)); 
		img1.positions.add( new Position(26, 112, false)); 
		img1.positions.add( new Position(26, 111, false)); 
		img1.positions.add( new Position(26, 110, false)); 
		img1.positions.add( new Position(25, 110, false)); 
		img1.positions.add( new Position(25, 109, false)); 
		img1.positions.add( new Position(25, 108, false)); 
		img1.positions.add( new Position(24, 107, false)); 
		img1.positions.add( new Position(24, 106, false)); 
		img1.positions.add( new Position(24, 105, false)); 
		img1.positions.add( new Position(23, 105, false)); 
		img1.positions.add( new Position(23, 104, false)); 
		img1.positions.add( new Position(23, 103, false)); 
		img1.positions.add( new Position(23, 102, false)); 
		img1.positions.add( new Position(22, 102, false)); 
		img1.positions.add( new Position(22, 101, false)); 
		img1.positions.add( new Position(22, 100, false)); 
		img1.positions.add( new Position(22, 99, false)); 
		img1.positions.add( new Position(21, 99, false)); 
		img1.positions.add( new Position(21, 98, false)); 
		img1.positions.add( new Position(21, 97, false)); 
		img1.positions.add( new Position(21, 96, false)); 
		img1.positions.add( new Position(21, 95, false)); 
		img1.positions.add( new Position(20, 95, false)); 
		img1.positions.add( new Position(20, 94, false)); 
		img1.positions.add( new Position(20, 93, false)); 
		img1.positions.add( new Position(20, 92, false)); 
		img1.positions.add( new Position(20, 91, false)); 
		img1.positions.add( new Position(20, 90, false)); 
		img1.positions.add( new Position(19, 90, false)); 
		img1.positions.add( new Position(19, 89, false)); 
		img1.positions.add( new Position(19, 88, false)); 
		img1.positions.add( new Position(19, 87, false)); 
		img1.positions.add( new Position(19, 86, false)); 
		img1.positions.add( new Position(19, 85, false)); 
		img1.positions.add( new Position(19, 84, false)); 
		img1.positions.add( new Position(19, 83, false)); 
		img1.positions.add( new Position(19, 82, false)); 
		img1.positions.add( new Position(19, 81, false)); 
		img1.positions.add( new Position(19, 80, false)); 
		img1.positions.add( new Position(19, 79, false)); 
		img1.positions.add( new Position(19, 78, false)); 
		img1.positions.add( new Position(19, 77, false)); 
		img1.positions.add( new Position(19, 76, false)); 
		img1.positions.add( new Position(19, 75, false)); 
		img1.positions.add( new Position(19, 74, false)); 
		img1.positions.add( new Position(19, 73, false)); 
		img1.positions.add( new Position(19, 72, false)); 
		img1.positions.add( new Position(19, 71, false)); 
		img1.positions.add( new Position(19, 70, false)); 
		img1.positions.add( new Position(20, 69, false)); 
		img1.positions.add( new Position(20, 68, false)); 
		img1.positions.add( new Position(20, 67, false)); 
		img1.positions.add( new Position(20, 66, false)); 
		img1.positions.add( new Position(21, 65, false)); 
		img1.positions.add( new Position(21, 64, false)); 
		img1.positions.add( new Position(21, 63, false)); 
		img1.positions.add( new Position(22, 62, false)); 
		img1.positions.add( new Position(22, 61, false)); 
		img1.positions.add( new Position(22, 60, false)); 
		img1.positions.add( new Position(23, 60, false)); 
		img1.positions.add( new Position(23, 59, false)); 
		img1.positions.add( new Position(23, 58, false)); 
		img1.positions.add( new Position(24, 58, false)); 
		img1.positions.add( new Position(24, 57, false)); 
		img1.positions.add( new Position(25, 56, false)); 
		img1.positions.add( new Position(25, 55, false)); 
		img1.positions.add( new Position(26, 55, false)); 
		img1.positions.add( new Position(26, 54, false)); 
		img1.positions.add( new Position(27, 53, false)); 
		img1.positions.add( new Position(27, 52, false)); 
		img1.positions.add( new Position(28, 52, false)); 
		img1.positions.add( new Position(28, 51, false)); 
		img1.positions.add( new Position(29, 51, false)); 
		img1.positions.add( new Position(29, 50, false)); 
		img1.positions.add( new Position(30, 50, false)); 
		img1.positions.add( new Position(30, 49, false)); 
		img1.positions.add( new Position(31, 49, false)); 
		img1.positions.add( new Position(31, 48, false)); 
		img1.positions.add( new Position(32, 48, false)); 
		img1.positions.add( new Position(32, 47, false)); 
		img1.positions.add( new Position(33, 47, false)); 
		img1.positions.add( new Position(33, 46, false)); 
		img1.positions.add( new Position(34, 46, false)); 
		img1.positions.add( new Position(35, 46, false)); 
		img1.positions.add( new Position(35, 45, false)); 
		img1.positions.add( new Position(36, 45, false)); 
		img1.positions.add( new Position(36, 44, false)); 
		img1.positions.add( new Position(37, 44, false)); 
		img1.positions.add( new Position(38, 44, false)); 
		img1.positions.add( new Position(38, 43, false)); 
		img1.positions.add( new Position(39, 43, false)); 
		img1.positions.add( new Position(40, 43, false)); 
		img1.positions.add( new Position(40, 42, false)); 
		img1.positions.add( new Position(41, 42, false)); 
		img1.positions.add( new Position(42, 42, false)); 
		img1.positions.add( new Position(43, 41, false)); 
		img1.positions.add( new Position(44, 41, false)); 
		img1.positions.add( new Position(45, 41, false)); 
		img1.positions.add( new Position(46, 41, false)); 
		img1.positions.add( new Position(46, 40, false)); 
		img1.positions.add( new Position(47, 40, false)); 
		img1.positions.add( new Position(48, 40, false)); 
		img1.positions.add( new Position(49, 40, false)); 
		img1.positions.add( new Position(50, 40, false)); 
		img1.positions.add( new Position(51, 40, false)); 
		img1.positions.add( new Position(52, 40, false)); 
		img1.positions.add( new Position(53, 40, false)); 
		img1.positions.add( new Position(54, 40, false)); 
		img1.positions.add( new Position(55, 40, false)); 
		img1.positions.add( new Position(56, 40, false)); 
		img1.positions.add( new Position(57, 40, false)); 
		img1.positions.add( new Position(58, 40, false)); 
		img1.positions.add( new Position(59, 41, false)); 
		img1.positions.add( new Position(60, 41, false)); 
		img1.positions.add( new Position(61, 41, false)); 
		img1.positions.add( new Position(62, 41, false)); 
		img1.positions.add( new Position(63, 42, false)); 
		img1.positions.add( new Position(64, 42, false)); 
		img1.positions.add( new Position(65, 42, false)); 
		img1.positions.add( new Position(66, 43, false)); 
		img1.positions.add( new Position(67, 43, false)); 
		img1.positions.add( new Position(68, 43, false)); 
		img1.positions.add( new Position(68, 44, false)); 
		img1.positions.add( new Position(69, 44, false)); 
		img1.positions.add( new Position(70, 44, false)); 
		img1.positions.add( new Position(71, 44, false)); 
		img1.positions.add( new Position(71, 45, false)); 
		img1.positions.add( new Position(72, 45, false)); 
		img1.positions.add( new Position(73, 45, false)); 
		img1.positions.add( new Position(74, 45, false)); 
		img1.positions.add( new Position(75, 45, false)); 
		img1.positions.add( new Position(76, 45, false)); 
		img1.positions.add( new Position(77, 45, false)); 
		img1.positions.add( new Position(78, 45, false)); 
		img1.positions.add( new Position(79, 45, false)); 
		img1.positions.add( new Position(80, 45, false)); 
		img1.positions.add( new Position(80, 44, false)); 
		img1.positions.add( new Position(81, 44, false)); 
		img1.positions.add( new Position(82, 44, false)); 
		img1.positions.add( new Position(83, 44, false)); 
		img1.positions.add( new Position(83, 43, false)); 
		img1.positions.add( new Position(84, 43, false)); 
		img1.positions.add( new Position(85, 43, false)); 
		img1.positions.add( new Position(86, 43, false)); 
		img1.positions.add( new Position(86, 42, false)); 
		img1.positions.add( new Position(87, 42, false)); 
		img1.positions.add( new Position(88, 42, false)); 
		img1.positions.add( new Position(89, 41, false)); 
		img1.positions.add( new Position(90, 41, false)); 
		img1.positions.add( new Position(91, 41, false)); 
		img1.positions.add( new Position(92, 40, false)); 
		img1.positions.add( new Position(93, 40, false)); 
		img1.positions.add( new Position(94, 40, false)); 
		img1.positions.add( new Position(95, 40, false)); 
		img1.positions.add( new Position(96, 40, false)); 
		img1.positions.add( new Position(97, 39, false)); 
		img1.positions.add( new Position(96, 40, false)); 
		img1.positions.add( new Position(96, 40, true)); 
		
		//CHAPTER 3: init start drawing //TODO: sometimes head-switch error; no "drive to x while head up"
		

		LCD.drawString("driving home", 0, 0);
		LCD.drawString("for christmas", 1, 1);
		myRobot.driveToHome(myRobot.headPos); // both speeds are very good //positive integer drive towards sensor
		//CHAPTER 4: moving & printing to all positions
		int a = 0;
		for (Position b : img1.positions) {
			//LCD.clear();
			LCD.drawString("[" + a + "/" + img1.positions.size() + "]", 0, 1);
			LCD.drawString("real: "+ myRobot.realPosX + ", " + myRobot.realPosY, 0, 2);
			LCD.drawString("thres: "+myRobot.thresholdX + ", " + myRobot.thresholdY, 0, 3);
			LCD.drawString("Take a hike,", 0, 6);
			LCD.drawString("be curious", 1, 7);

			if (b.headSwitch) {
				myRobot.headSwitch();
			}
			myRobot.moveToPos(b.x, b.y);

			a++;

			//Delay.msDelay(10);
		}

		//CHAPTER 5: cleanup at the end of the printing
		LCD.clear();
		LCD.drawString("RESET ...", 0, 0);
		//TODO: kill me because the head is always up at the end
		if (myRobot.headPos) { //if down, move up
			myRobot.headSwitch();
		}

		//TODO: maybe calculate required Y movement?
		myRobot.move(0, 250);
		
		myRobot.headUp(); //move him down at the end

		myRobot.chainMotor.stop();
		myRobot.wheelMotor.stop();
		myRobot.headMotor.stop();
	}

}